version: "3.8"

services:
  heallink:
    build:
      context: .
      dockerfile: ./apps/heallink/Dockerfile.dev
    container_name: heallink
    ports:
      - "3000:3000"
    volumes:
      - ./apps/heallink:/app/apps/heallink
      - ./packages:/app/packages
      - heallink-node-modules:/app/apps/heallink/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - API_URL=http://api:3003
    depends_on:
      - api
    networks:
      - heallink-network
    restart: unless-stopped

  heallink-admin:
    build:
      context: .
      dockerfile: ./apps/heallink-admin/Dockerfile.dev
    container_name: heallink-admin
    ports:
      - "3001:3001"
    volumes:
      - ./apps/heallink-admin:/app/apps/heallink-admin
      - ./packages:/app/packages
      - heallink-admin-node-modules:/app/apps/heallink-admin/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3001
      - API_URL=http://api:3003
    depends_on:
      - api
    networks:
      - heallink-network
    restart: unless-stopped

  heallink-providers:
    build:
      context: .
      dockerfile: ./apps/heallink-providers/Dockerfile.dev
    container_name: heallink-providers
    ports:
      - "3002:3002"
    volumes:
      - ./apps/heallink-providers:/app/apps/heallink-providers
      - ./packages:/app/packages
      - heallink-providers-node-modules:/app/apps/heallink-providers/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3002
      - API_URL=http://api:3003
    depends_on:
      - api
    networks:
      - heallink-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    container_name: heallink-api
    ports:
      - "3003:3003"
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - api-node-modules:/app/apps/api/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=mongodb://mongodb:27018/heallink
      - JWT_SECRET=dev-jwt-secret-key
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_SECRET=dev-jwt-refresh-secret-key
      - JWT_REFRESH_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3001,http://localhost:3002
    depends_on:
      - mongodb
    networks:
      - heallink-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: heallink-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=heallink
    networks:
      - heallink-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express
    container_name: heallink-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27018
    depends_on:
      - mongodb
    networks:
      - heallink-network

networks:
  heallink-network:
    driver: bridge

volumes:
  heallink-node-modules:
  heallink-admin-node-modules:
  heallink-providers-node-modules:
  api-node-modules:
  mongodb-data:
