// List of countries with dial codes and emoji flags
const countries = [
  { name: "United States", code: "US", dial_code: "+1", emoji: "🇺🇸" },
  { name: "United Kingdom", code: "GB", dial_code: "+44", emoji: "🇬🇧" },
  { name: "Canada", code: "CA", dial_code: "+1", emoji: "🇨🇦" },
  { name: "Afghanistan", code: "AF", dial_code: "+93", emoji: "🇦🇫" },
  { name: "Albania", code: "AL", dial_code: "+355", emoji: "🇦🇱" },
  { name: "Algeria", code: "DZ", dial_code: "+213", emoji: "🇩🇿" },
  { name: "Argentina", code: "AR", dial_code: "+54", emoji: "🇦🇷" },
  { name: "Australia", code: "AU", dial_code: "+61", emoji: "🇦🇺" },
  { name: "Austria", code: "AT", dial_code: "+43", emoji: "🇦🇹" },
  { name: "Bahrain", code: "BH", dial_code: "+973", emoji: "🇧🇭" },
  { name: "Bangladesh", code: "BD", dial_code: "+880", emoji: "🇧🇩" },
  { name: "Belgium", code: "BE", dial_code: "+32", emoji: "🇧🇪" },
  { name: "Brazil", code: "BR", dial_code: "+55", emoji: "🇧🇷" },
  { name: "China", code: "CN", dial_code: "+86", emoji: "🇨🇳" },
  { name: "Colombia", code: "CO", dial_code: "+57", emoji: "🇨🇴" },
  { name: "Denmark", code: "DK", dial_code: "+45", emoji: "🇩🇰" },
  { name: "Egypt", code: "EG", dial_code: "+20", emoji: "🇪🇬" },
  { name: "France", code: "FR", dial_code: "+33", emoji: "🇫🇷" },
  { name: "Germany", code: "DE", dial_code: "+49", emoji: "🇩🇪" },
  { name: "Ghana", code: "GH", dial_code: "+233", emoji: "🇬🇭" },
  { name: "Greece", code: "GR", dial_code: "+30", emoji: "🇬🇷" },
  { name: "Hong Kong", code: "HK", dial_code: "+852", emoji: "🇭🇰" },
  { name: "India", code: "IN", dial_code: "+91", emoji: "🇮🇳" },
  { name: "Indonesia", code: "ID", dial_code: "+62", emoji: "🇮🇩" },
  { name: "Iran", code: "IR", dial_code: "+98", emoji: "🇮🇷" },
  { name: "Iraq", code: "IQ", dial_code: "+964", emoji: "🇮🇶" },
  { name: "Ireland", code: "IE", dial_code: "+353", emoji: "🇮🇪" },
  { name: "Israel", code: "IL", dial_code: "+972", emoji: "🇮🇱" },
  { name: "Italy", code: "IT", dial_code: "+39", emoji: "🇮🇹" },
  { name: "Japan", code: "JP", dial_code: "+81", emoji: "🇯🇵" },
  { name: "Kenya", code: "KE", dial_code: "+254", emoji: "🇰🇪" },
  { name: "Korea, South", code: "KR", dial_code: "+82", emoji: "🇰🇷" },
  { name: "Malaysia", code: "MY", dial_code: "+60", emoji: "🇲🇾" },
  { name: "Mexico", code: "MX", dial_code: "+52", emoji: "🇲🇽" },
  { name: "Morocco", code: "MA", dial_code: "+212", emoji: "🇲🇦" },
  { name: "Netherlands", code: "NL", dial_code: "+31", emoji: "🇳🇱" },
  { name: "New Zealand", code: "NZ", dial_code: "+64", emoji: "🇳🇿" },
  { name: "Nigeria", code: "NG", dial_code: "+234", emoji: "🇳🇬" },
  { name: "Norway", code: "NO", dial_code: "+47", emoji: "🇳🇴" },
  { name: "Pakistan", code: "PK", dial_code: "+92", emoji: "🇵🇰" },
  { name: "Philippines", code: "PH", dial_code: "+63", emoji: "🇵🇭" },
  { name: "Poland", code: "PL", dial_code: "+48", emoji: "🇵🇱" },
  { name: "Portugal", code: "PT", dial_code: "+351", emoji: "🇵🇹" },
  { name: "Qatar", code: "QA", dial_code: "+974", emoji: "🇶🇦" },
  { name: "Romania", code: "RO", dial_code: "+40", emoji: "🇷🇴" },
  { name: "Russia", code: "RU", dial_code: "+7", emoji: "🇷🇺" },
  { name: "Saudi Arabia", code: "SA", dial_code: "+966", emoji: "🇸🇦" },
  { name: "Singapore", code: "SG", dial_code: "+65", emoji: "🇸🇬" },
  { name: "South Africa", code: "ZA", dial_code: "+27", emoji: "🇿🇦" },
  { name: "Spain", code: "ES", dial_code: "+34", emoji: "🇪🇸" },
  { name: "Sweden", code: "SE", dial_code: "+46", emoji: "🇸🇪" },
  { name: "Switzerland", code: "CH", dial_code: "+41", emoji: "🇨🇭" },
  { name: "Taiwan", code: "TW", dial_code: "+886", emoji: "🇹🇼" },
  { name: "Thailand", code: "TH", dial_code: "+66", emoji: "🇹🇭" },
  { name: "Turkey", code: "TR", dial_code: "+90", emoji: "🇹🇷" },
  { name: "Ukraine", code: "UA", dial_code: "+380", emoji: "🇺🇦" },
  { name: "United Arab Emirates", code: "AE", dial_code: "+971", emoji: "🇦🇪" },
  { name: "Vietnam", code: "VN", dial_code: "+84", emoji: "🇻🇳" }
];

export default countries;