# Avatar Engine Configuration File
# This file defines available avatars and their properties

avatars:
  doctor_avatar_1:
    name: "Dr. Sarah Chen"
    description: "Professional female doctor avatar"
    model_file: "doctor_female_01.glb"
    texture_sets:
      - "doctor_female_01_diffuse.jpg"
      - "doctor_female_01_normal.jpg"
      - "doctor_female_01_roughness.jpg"
    blend_shapes:
      - "mouth_open"
      - "mouth_smile"
      - "mouth_frown"
      - "eyebrow_up"
      - "eyebrow_down"
      - "eye_blink"
      - "jaw_open"
    default_emotion: "neutral"
    background: "medical_office"
    
  doctor_avatar_2:
    name: "Dr. Michael Rodriguez"
    description: "Professional male doctor avatar"
    model_file: "doctor_male_01.glb"
    texture_sets:
      - "doctor_male_01_diffuse.jpg"
      - "doctor_male_01_normal.jpg"
      - "doctor_male_01_roughness.jpg"
    blend_shapes:
      - "mouth_open"
      - "mouth_smile"
      - "mouth_frown"
      - "eyebrow_up"
      - "eyebrow_down"
      - "eye_blink"
      - "jaw_open"
    default_emotion: "neutral"
    background: "medical_office"
    
  nurse_avatar_1:
    name: "Nurse Jennifer Adams"
    description: "Friendly nurse avatar"
    model_file: "nurse_female_01.glb"
    texture_sets:
      - "nurse_female_01_diffuse.jpg"
      - "nurse_female_01_normal.jpg"
      - "nurse_female_01_roughness.jpg"
    blend_shapes:
      - "mouth_open"
      - "mouth_smile"
      - "mouth_frown"
      - "eyebrow_up"
      - "eyebrow_down"
      - "eye_blink"
      - "jaw_open"
    default_emotion: "happy"
    background: "clinic_room"

backgrounds:
  medical_office:
    name: "Medical Office"
    description: "Professional medical office environment"
    image_file: "medical_office.jpg"
    lighting:
      ambient: [0.3, 0.3, 0.3]
      directional: [0.8, 0.8, 0.8]
      direction: [-0.5, -1.0, -0.5]
      
  clinic_room:
    name: "Clinic Room"
    description: "Bright clinic examination room"
    image_file: "clinic_room.jpg"
    lighting:
      ambient: [0.4, 0.4, 0.4]
      directional: [0.9, 0.9, 0.9]
      direction: [-0.3, -1.0, -0.2]
      
  hospital_corridor:
    name: "Hospital Corridor"
    description: "Modern hospital hallway"
    image_file: "hospital_corridor.jpg"
    lighting:
      ambient: [0.35, 0.35, 0.35]
      directional: [0.7, 0.7, 0.7]
      direction: [0.0, -1.0, -0.3]

# Default configuration
defaults:
  avatar_id: "doctor_avatar_1"
  background_id: "medical_office"
  video_quality: "high"
  lip_sync_model: "rhubarb"
  emotion_transitions: true
  auto_blink: true
  head_movement: true

# Performance presets
performance:
  ultra:
    resolution: "4K"
    fps: 60
    quality: "ultra"
    antialiasing: true
    shadows: true
    reflections: true
    
  high:
    resolution: "1080p"
    fps: 30
    quality: "high"
    antialiasing: true
    shadows: true
    reflections: false
    
  medium:
    resolution: "1080p"
    fps: 30
    quality: "medium"
    antialiasing: false
    shadows: false
    reflections: false
    
  low:
    resolution: "720p"
    fps: 24
    quality: "low"
    antialiasing: false
    shadows: false
    reflections: false